# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Adolphor
author: adolphor
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  学习笔记，技术分享，包括但不限于：
  Java，JVM，Spring，Spring MVC，myBatis，Tomcat，Maven，Git，Intellij
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://www.adolphor.com" # the base hostname & protocol for your site
twitter_username: 0haizhu0
github_username:  NorthFacing

# paginate
gems: [jekyll-paginate]
paginate: 10

# Build settings
markdown: kramdown

# 多说
duoshuoId: adolphor

# disqus
disqusId: adolphor

# google 分析
googleAnalyticsId: UA-68980203-2

sass:
    sass_dir: ./css/_sass
    style: compressed

cacheVersion: 20170223